# using this config as the configuration file


config = {'average_reset_epoch_interval': 30,
'checkpoints': [0,1,10],
'distributed_backend': 'nccl',
'fix_conv_weight_norm': False,
'log_verbosity': 1,
'n_workers': 4,
'num_epochs': 60,
'num_train_tracking_batches': 1,
'optimizer_batch_size': 16,
'optimizer_conv_learning_rate': 1.25,
'optimizer_decay_at_epochs': [45, 55],
'optimizer_decay_with_factor': 10.0,
'optimizer_learning_rate': 0.1,
'optimizer_mom_before_reduce': False,
'optimizer_momentum_type': 'nesterov',
'optimizer_momentum': 0.0,
'optimizer_scale_lr_with_factor': 16,
'optimizer_scale_lr_with_warmup_epochs': 5,
'optimizer_wd_before_reduce': False,
'optimizer_weight_decay_bn': 0.0,
'optimizer_weight_decay_conv': 0.0,
'optimizer_weight_decay_other': 0.0,
'rank': 0,
'local_rank': 0,
'seed': 1,
'task_architecture': 'ResNet18',
'task': 'LanguageModeling',
'dataset_name': 'wikitext2',
'optimizer_reducer': 'Sketch_Embed_Reducer',
'optimizer_memory': False,
'optimizer_reducer_rank': 0.001,
'optimizer_sparsity': 0.01,
'optimizer_reducer_reuse_sketch': False,
'warm_reducer': False
}

config_res = {'average_reset_epoch_interval': 30,
'checkpoints': [0,1,10],
'distributed_backend': 'gloo',
'fix_conv_weight_norm': False,
'log_verbosity': 1,
'n_workers': 16,
'num_epochs': 30,
'num_train_tracking_batches': 1,
'optimizer_batch_size': 128,
'optimizer_conv_learning_rate': 0.1,
'optimizer_decay_at_epochs': [15, 25],
'optimizer_decay_with_factor': 10.0,
'optimizer_learning_rate': 0.1,
'optimizer_mom_before_reduce': False,
'optimizer_momentum_type': 'nesterov',
'optimizer_momentum': 0.9,
'optimizer_scale_lr_with_factor': 16,
'optimizer_scale_lr_with_warmup_epochs': 5,
'optimizer_wd_before_reduce': False,
'optimizer_weight_decay_bn': 0.0,
'optimizer_weight_decay_conv': 0.0001,
'optimizer_weight_decay_other': 0.0001,
'seed': 1,
'task_architecture': 'ResNet34',
'task': 'Cifar',
'dataset_name': 'cifar100',
'optimizer_reducer': 'CAS_Fast_Reducer',
'optimizer_memory': True,
'optimizer_reducer_rank': 3,
'lss_table_size': [200000, 300000, 10000, 10000, 10000, 10000, 300000, 200000],
'warm_reducer': True,
'rank': 0,
'local_rank': 0
}